### ISSUE TITLE
MVP Requirements

### ISSUE THREAD

**Issue by flakey5** [platformatic/ai-warp-old#1]
# Minimum requirements for basic functionality
 * [x] Configuration
   * [x] Prompt prefixes/suffixes
   * [x] Editing/filtering response before sending to client
 * [x] Proxying to/from AI models
   * [x] Decide on basic AI models to use (OpenAI, any other providers?)
   * [x] Backend
     * [x] Endpoint that takes prompt and AI model and sends it to the AI & returns the result
     * [x] Streaming
 * [x] Authentication (OpenID via Auth0, etc.)
   * [x] Backend
     * [x] Prompt endpoint requires auth JWT
 * [ ] Deployment
   * [x] Ability to package as a Stackable
   * [ ] Added to Meraki

# Additional Features
 * [x] Rate limiting (premium users having higher rate limits, etc.)
 * [ ] Storing prompt & responses for ???
   * [ ] Look into use cases for this

**Comment by mcollina** [comment]
Some things that are missing:

1. adding a custom prompt (both in config and via a Fastify decorator)
2. editing/filtering the response before returning it
3. editing the data received from the API before they are assembled together with the prompt

**Comment by mcollina** [comment]
Something useful would be to support an "Open Source" model (ollama?), that can ideally be run on Digital Ocean or some of those kind of hosting.
