### ISSUE TITLE
hide scroll bars

### ISSUE THREAD

**Issue by mcollina** [platformatic/ai-warp-old#107]
![Screenshot 2024-07-18 at 10 12 47](https://github.com/user-attachments/assets/c7bca6ee-03e1-41d0-95f1-4b44afd85c05)

**Comment by iamfortune** [comment]
It's probably a resolution that you are currently viewing. I've attached an image of the same prompt on my machine. @mcollina 

<img width="1512" alt="Screenshot 2024-07-23 at 12 26 35 PM" src="https://github.com/user-attachments/assets/76043798-fb45-43db-a614-1d74df80a25c">

**Comment by mcollina** [comment]
Closing for now, I'll ping again if I can reproduce this more reliably.
