### ISSUE TITLE
Create Simple “default” UI for querying the LLMs.

### ISSUE THREAD

**Issue by mcollina** [platformatic/ai-warp-old#23]
I would recommend something incredibly simple to replace the default “root” homepage.

**Comment by iamfortune** [comment]
Something like a search bar and a button for simple prompts with a results bar for responses from LLMs? @mcollina

**Comment by mcollina** [comment]
yes. Would be best if it's without frameworks and not transpiled (easier to maintain).

**Comment by mcollina** [comment]
@Fmusso94 can help with the design if needed

**Comment by flakey5** [comment]
Basic UI landed in #30 until we get the design
