### ISSUE TITLE
editing/filtering the response before returning it

### ISSUE THREAD

**Issue by mcollina** [platformatic/ai-warp-old#24]

**Comment by flakey5** [comment]
Aren't both this and #25 possible with the [preResponseCallback](https://github.com/platformatic/ai-warp/blob/main/docs/plugin-api.md#fastifyaipreresponsecallback) and [preResponseChunkCallback](https://github.com/platformatic/ai-warp/blob/main/docs/plugin-api.md#fastifyaipreresponsecallback)?

**Comment by mcollina** [comment]
Absolutely! I missed them
