### ISSUE TITLE
UI cutting down when scaling to smaller screens

### ISSUE THREAD

**Issue by mcollina** [platformatic/ai-warp-old#48]
<img width="1512" alt="Screenshot 2024-05-11 at 07 48 51" src="https://github.com/platformatic/ai-warp/assets/52195/15f88cc2-2150-4c7b-9307-558234303317">

Specifically, the bottom part is cut out.

**Comment by flakey5** [comment]
Hmm, I'm not sure what we could do for this. Decreasing the height for the illustration causes it to decrease in both height and width (attached), even if we fix the width to a set amount the illustration might start looking a little weird.
![image](https://github.com/platformatic/ai-warp/assets/73616808/1a652467-898b-496f-bab6-9031d1be9754)

How do we feel about decreasing the padding between the welcome banner and the prompt suggestions then?
